### ISSUE TITLE
Error installing on Hoobs. Plugin site not available 

### ISSUE THREAD

**Issue by farkis644** [sajmonr/homebridge-hubspace#1]
Hey. Thanks for putting this together. Very excited to try it out. Unfortunately I am having issues installing. Any suggestions? See attached. 

<img width="1861" alt="Screenshot 2023-02-25 at 9 09 34 AM" src="https://user-images.githubusercontent.com/2440703/221361652-d5edde4f-db88-402e-9eb5-685c298574a3.png">
<img width="803" alt="Screenshot 2023-02-25 at 9 09 47 AM" src="https://user-images.githubusercontent.com/2440703/221361656-c7879aa6-07ab-4186-a448-f19b260a25d9.png">
<img width="744" alt="Screenshot 2023-02-25 at 9 09 50 AM" src="https://user-images.githubusercontent.com/2440703/221361661-debcde88-999a-4a31-bdc8-791e5c4f38a9.png">

**Comment by sajmonr** [comment]
Hey. I'm not seeing anything obvious from the screenshots. The error EAI_AGAIN suggests trouble with DNS or reaching the registry itself. Is there any chance that you are behind a proxy or VPN?

**Comment by farkis644** [comment]
Actually I am having issues with turning the fan off. When I turn off in HomeKit, it will say it’s off for about 5 seconds then turn back on. The fan never actually turns off. Thoughts?Sent from my iPhoneOn Feb 27, 2023, at 10:04 AM, Adam ***@***.***> wrote:﻿
Hey. I'm not seeing anything obvious from the screenshots. The error EAI_AGAIN suggests trouble with DNS or reaching the registry itself. Is there any chance that you are behind a proxy or VPN?

**Comment by sajmonr** [comment]
Hi,
thanks for the report and sorry you are having issues. I've opened a new issue for this here: #5
